[package]
name = "bluefin-solo-player"
version = "0.1.0"
edition = "2021"

[dependencies]
botris = {path = "../../lib/botris"}
mino = {path = "../../lib/mino"}
bluefin = {path = "../../lib/bluefin"}

tracing = {version = "0.1"}
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
anyhow = {version = "1"}
